name: Netease Recent Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '00 22 * * 0'
env:
  NETEASE_ID: ${{ secrets.NETEASE_ID }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: zonemeen/netease-recent-actions@v1.0.23
        with:
          id: ${{ env.NETEASE_ID }}
          size: 60
